[package]
name = "tokio-mock-task"
# When releasing to crates.io:
# - Update html_root_url.
# - Create "v0.1.x" git tag.
version = "0.1.1"
authors = ["Carl Lerche <me@carllerche.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/carllerche/tokio-mock-task"
homepage = "https://github.com/carllerche/tokio-mock-task"
documentation = "https://docs.rs/tokio-mock-task/0.1.0"
description = """
Mock a Tokio task
"""

[dependencies]
futures = "0.1.21"
